use_frameworks!

platform :ios, '8.0'

target 'LPPermanentThread_Example' do
  pod 'LPPermanentThread', :path => '../'

  target 'LPPermanentThread_Tests' do
    inherit! :search_paths

    
  end
end
